### ISSUE TITLE
out of toilet paper

### ISSUE THREAD

**Issue by m0ose** [RedfishGroup/code-club#3]
We're out of toilet paper at the office and have resorted to using pages from old actionscript reference books to wipe with.

**Comment by mariusnita** [comment]
Hahaha!

**Comment by stephenguerin** [comment]
is this a serious pull request?

**Comment by mariusnita** [comment]
Hahhaha!

**Comment by stephenguerin** [comment]
How often do you wipe your cache?

--- -. .   ..-. .. ... ....   - .-- ---   ..-. .. ... ....
Stephen.Guerin@Redfish.com
1600 Lena St #D1, Santa Fe, NM 87505
office: (505) 995-0206  mobile: (505) 577-5828
tw: @redfishgroup  skype: redfishgroup
redfish.com  |  simtable.com
